<?php

namespace App\Http\Controllers\Backend;


use Illuminate\Http\Request;

class UserController extends BackendController
{
    public function index(Request $request)
    {
        parent::index($request); // TODO: Change the autogenerated stub
    }

}